spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/clinic_booking"
    username: root
    password: Kien2003#
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8081




