spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/clinic_booking"
    username: root
    password: 28122003
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey  # Dùng "apikey" thay cho tên người dùng
    password:   # Thay bằng API Key của bạn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8081

jwt:
  signerKey: "mqa0vyq2l6R+h8A421RSbG572s14p8J6QU7ofdhMH3LS9ZhUlJ7SWjz+O/ozXo6b"

openai:
  api:
    key: "xxx"