spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/clinic_booking"
    username: root
    password: Kien2003#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
  servlet:
    context-path: /clinic

jwt:
  signerKey: "mqa0vyq2l6R+h8A421RSbG572s14p8J6QU7ofdhMH3LS9ZhUlJ7SWjz+O/ozXo6b"